# -*- coding: utf-8 -*-
"""Data Preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUfjeaOoVIWy3WiIQX9-rGY_uZKn-yPT
"""

import os
import shutil
import glob
from tqdm import tqdm

!unzip -FF /content/mrlEyes_2018_01.zip

"""subject ID:
xxx

image number:
xxx

gender:
0 - male
1 - famale

glasses:
0 - no
1 - yes

eye state:
0 - close
1 - open

reflections:
0 - none
1 - low
2 - high

lighting conditions/image quality:
0 - bad
1 - good

sensor type:
01 - RealSense SR300 640x480
02 - IDS Imaging, 1280x1024
03 - Aptina Imagin 752x480

example:
s001_00123_0_0_0_0_0_01.png
"""

Raw_DIR=r'/content/mrlEyes_2018_01'

for dirpath, dirname, filenames in os.walk(Raw_DIR):
    for i in tqdm([f for f in filenames if f.endswith('.png')]):
        if i.split ('_')[4]=='0':
            shutil.copy(src=dirpath+'/'+i, dst=r'/content/Prepared Data/Closed Eyes')
        elif i.split ('_')[4]=='1':
            shutil.copy(src=dirpath+'/'+i, dst=r'/content/Prepared Data/Open Eyes')

!pip install --upgrade pip

!apt-get install -y python3.10-venv

!python3 -m venv my_venv
!source my_venv/bin/activate

!pip install split-folders

import splitfolders
input_folders = r'/content/Prepared Data'
splitfolders.ratio(input_folders, output='Prepared_Data(2)', ratio=(.8, .2), group_prefix = None)



from google.colab import drive
drive.mount('/content/drive')